baseURL: "https://chinabox49101.github.io/"
title: 中国社会热点网
pagination.pagerSize: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

languageCode: "en-us" 

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Categories
          url: categories/
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "分享中国国内社会的热点事件并讨论"
  author: Me
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  images: ["papermod-cover.png"]

# 是否启用评论功能
  comments: true
  #评论设置
  giscus:
    repo: "ChinaBox49101/chinabox49101.github.io"
    repoid: "R_kgDONhFO5g"
    category: "Announcements"
    categoryid: "DIC_kwDONhFO5s4CldKy"
    mapping: "title"
    strict: "1"
    reactionsEnabled: "1"
    emitMetadata: "0"
    inputPosition: "top"
    theme: "preferred_color_scheme"
    lang: "zh-CN"
    crossorigin: "anonymous"

  profileMode:
    enabled: false
    title: Me
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "网站声明"
    Content: >
      本网站为开放式匿名评论网站，欢迎**关注、转发、记录、补充**

      - **推动司法独立，民主建设** 是我们共同的目标

      - 若有案件热点事件，请联系chinabox49101@gmail.com（请尽量附上时间、地址、人物、经过）

      - 最新网址欢迎关注下方Github仓库

  socialIcons:
    - name: github
      url: "https://github.com/ChinaBox49101/chinabox49101.github.io/"
    - name: Telegram
      url: "https://t.me/jiangxilyx"
    - name: RsS
      url: "index.xml"

  editPost:
    URL: "https://github.com/ChinaBox49101/chinabox49101.github.io/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true